# Generated by Django 3.2.22 on 2023-10-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmanager',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID чата'),
        ),
        migrations.AddField(
            model_name='student',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='ID чата'),
        ),
    ]
