# Generated by Django 3.2 on 2023-10-28 17:59

from django.db import migrations


def create_base_weeks(apps, schema_editor):
    Week = apps.get_model('projects', 'Week')
    Week.objects.bulk_create(
        [Week(name=f"{index + 1} неделя") for index in range(4)]
    )


class Migration(migrations.Migration):
    dependencies = [
        ('projects', '0003_auto_20231028_2110'),
    ]

    operations = [
        migrations.RunPython(create_base_weeks)
    ]
